"""project table patch 1.0

Revision ID: 888f72dd56f2
Revises: 
Create Date: 2019-05-06 14:54:31.851266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888f72dd56f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=32), nullable=True),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pwhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecturer_email'), 'lecturer', ['email'], unique=True)
    op.create_index(op.f('ix_lecturer_token'), 'lecturer', ['token'], unique=True)
    op.create_index(op.f('ix_lecturer_username'), 'lecturer', ['username'], unique=True)
    op.create_table('student',
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=32), nullable=True),
    sa.Column('lastname', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('institution', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pwhash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_token'), 'student', ['token'], unique=True)
    op.create_index(op.f('ix_student_username'), 'student', ['username'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('submit_date', sa.DateTime(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('supervisor', sa.Integer(), nullable=True),
    sa.Column('requested_approval', sa.Boolean(), nullable=True),
    sa.Column('approval_req_accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['student.id'], ),
    sa.ForeignKeyConstraint(['supervisor'], ['lecturer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_index(op.f('ix_project_publish_date'), 'project', ['publish_date'], unique=False)
    op.create_index(op.f('ix_project_submit_date'), 'project', ['submit_date'], unique=False)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_submit_date'), table_name='project')
    op.drop_index(op.f('ix_project_publish_date'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_student_username'), table_name='student')
    op.drop_index(op.f('ix_student_token'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_lecturer_username'), table_name='lecturer')
    op.drop_index(op.f('ix_lecturer_token'), table_name='lecturer')
    op.drop_index(op.f('ix_lecturer_email'), table_name='lecturer')
    op.drop_table('lecturer')
    # ### end Alembic commands ###
