"""tokens

Revision ID: cfadb356b811
Revises: 0f6db914b53f
Create Date: 2019-04-11 00:30:41.782297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfadb356b811'
down_revision = '0f6db914b53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('lecturer', sa.Column('token_expiration_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_lecturer_token'), 'lecturer', ['token'], unique=True)
    op.add_column('student', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('student', sa.Column('token_expiration_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_student_token'), 'student', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_token'), table_name='student')
    op.drop_column('student', 'token_expiration_date')
    op.drop_column('student', 'token')
    op.drop_index(op.f('ix_lecturer_token'), table_name='lecturer')
    op.drop_column('lecturer', 'token_expiration_date')
    op.drop_column('lecturer', 'token')
    # ### end Alembic commands ###
